#------------------------------------------------------
# Demonstrative Script #1
# Simulated FPP signals generated by convolving
# a Poisson process with an arbitrary pulse
#------------------------------------------------------

# Replace myLocalPath with the path to PsiAnalysis_Functions.R and uncomment the next line
# source("myLocalPath/PsiAnalysis_Functions.R")

#------------------------------------------------------
# Signal Parameters
#------------------------------------------------------
fs <- 1000         # Sampling rate (samples per second)
total.time <- 5    # Total simulation time (seconds)
lambda_g <- 5000   # Pulse density of Poisson process (pulses per second)
lambda <- lambda_g / fs  # Pulse density at the sample-interval timing

# Total number of samples
n.samples <- fs * total.time

#------------------------------------------------------
# Generate Poisson Process and Pulse
#------------------------------------------------------
PP <- rpois(n.samples, lambda)  # Poisson process
PP <- PP - mean(PP)  # Ensure zero mean (AC signal)

# Define pulse (convolution kernel) as an alpha function with tau = 0.025
tau <- 0.025
pulse <- do.alpha.pulse(tau, fs, total.time)

# Normalize pulse energy to 1
pulse <- unitE(pulse)

# Generate simulated signal by convolving PP with the pulse
X <- convolve(pulse, rev(PP), type = "circular")

# Ensure signal has zero mean (simulate an AC signal)
X <- X - mean(X)

#------------------------------------------------------
# Visualization
#------------------------------------------------------
# Time axis
x.time <- seq(from = 0, by = 1 / fs, length.out = n.samples)

# Y-axis scaling (based on dispersion of process X)
y.scale <- 3.5 * sd(X)

# Plot Poisson process (light gray)
plot(
  x.time, PP, type = "l", col = "lightgray", ylim = c(-y.scale, y.scale),
  xlab = "Time (seconds)", ylab = "Signal Amplitude"
)

# Overlay process X (black)
lines(x.time, X, col = "black")

# Scale pulse for better visualization
pulse.peak <- max(pulse)
pulse.amp <- y.scale / pulse.peak
lines(x.time, pulse.amp * pulse, col = "red")

# Add title with scaled pulse information
title(
  paste0(
    "Poisson process (light gray), process X (black), and pulse (red). ",
    "Pulse is scaled = ", round(pulse.amp, 1), "x"
  )
)
