#------------------------------------------------------
# Demostrative script #1
# Simulated FPP signals generated by convolving
# a Poisson process with an arbitrary pulse
#------------------------------------------------------

#sampling rate (samples per second)
fs <- 1000
#total time (seconds)
total.time <- 5
#pulse density of poisson process lambda_g (pulses per second)
lambda_g <- 5000
#pulse density of poisson process lambda at the somple-interval timing
lambda <- lambda_g/fs
#total samples of the simulated signal
n.samples <- fs*total.time
#Poison process of arbitrary length and arbitrary pulse density
PP <- rpois(n.samples, lambda)
#Lets simulate an AC signal (zero mean)
PP <- PP - mean(PP)
#Lets define our pulse (convolution kernel) as an alpha function with tau = 0.05
tau <- 0.025
pulse <- do.alpha.pulse(tau, fs, total.time)
#Lets force the energy of the pulse to be 1
pulse <- unitE(pulse)
#Simulates signal is is the convolution of PP and am arbitrary pulse
X <- convolve(pulse, rev(PP), type = "circular")
#Lets simulate an AC signal (zero mean)
X <- X - mean(X)

#--------------------PLOTS-----------------------------------------------------
#------time axis scaling
x.time <- seq(from = 0, by = 1/fs, length.out = n.samples)
#-------y-axis scaling (based on the dispersion of process X)
y.scale <- 3.5*sd(X)
plot(x.time, PP, type="l", col="lightgray", ylim=c(-y.scale, y.scale), xlab = "time (seconds)", ylab = "signal amplitude")
lines(x.time, X)
#The pulse is small compared to the signal so lets scale it for the visualization
pulse.peak <- max(pulse)
pulse.amp <- y.scale/pulse.peak
lines(x.time, pulse.amp*pulse, col="red")
title(paste0("Poisson process (light gray), process X (black), and pulse (red). Pulse is scaled = ", round(pulse.amp, 1),"x"))
